"""lifekit.plan_forge.forge_plan — Generate SMART learning plans from ingested books via Ollama.

Pipeline:
    1. Fetch book context (first ~10 chunks) from SQLite
    2. Build prompt with book metadata + user intent + teaching method
    3. Call Ollama (ollama.chat)
    4. Validate response against Pydantic PlanResponse schema
    5. Insert plan + tasks in a single transaction

Usage from CLI:
    python -m lifekit.plan_forge.forge <book_id> \
        --intent "Learn basics" --weeks 4 --method feynman

Or programmatically:
    result = forge_plan("a1b2c3d4", intent="Learn Python", duration_weeks=4)
"""
from __future__ import annotations

import json
import os
import sqlite3
import uuid
from typing import Any, List, Optional

import ollama
from pydantic import BaseModel, Field

from lifekit.db.schema import get_connection


# ── TeachingMethod (const-set of recognised values) ────────────

ALLOWED_TEACHING_METHODS = frozenset({
    "auto", "socratic", "feynman", "analogical", "spaced_recall",
})
DEFAULT_TEACHING_METHOD = "socratic"


# Teaching-method instructions — injected into the system prompt.
_TEAChing_method_instructions: dict[str, str] = {
    "socratic": (
        "You are a Socratic tutor. Frame every task as guided inquiry rather than direct instruction. Use prompts like 'Consider this...?' or 'Ask yourself...' to push the learner toward self-discovery. Never give answers — always point toward deeper questions."
    ),
    "feynman": (
        "You are a Feynman-method coach. Frame every task as if teaching the concept to a complete beginner using simple analogies, daily-life metaphors, and plain language. Use prompts like 'Explain this to a 10-year-old...' or 'Draw an analogy between X and Y...'. Prioritise genuine understanding over memorization."
    ),
    "analogical": (
        "You are an analogical-reasoning coach. Frame every task around cross-domain mapping — connect the book's core ideas to unrelated areas like music, sports, cooking, city navigation, games, etc. Use prompts like 'Compare this to...' or 'Imagine X is a Y because...'. Build rich mental models through surprising connections."
    ),
    "spaced_recall": (
        "You are a spaced-repetition coach using the Leitner principle. Frame every task as active retrieval — never passive re-reading. Use prompts like 'Write down from memory...' or 'Before reading ahead, recall...'. Structure: days 1-3 = first recall with hints; days 4-7 = delayed recall (no material open); days 8+ = cumulative recall of all prior chapters.",
    ),
}


# ── Pydantic Models ───────────────────────


class TaskItem(BaseModel):
    """A single daily learning task generated by the model."""

    day: int = Field(..., gt=0, le=28)
    title: str = Field(..., min_length=3)
    description: str = Field(..., min_length=10)
    estimated_minutes: int = Field(..., ge=5, le=120)
    exercise_type: str = Field(..., min_length=3)
    context_source: Optional[str] = None


class PlanResponse(BaseModel):
    """Full plan returned by Ollama — a list of daily tasks."""

    weekly_plan: List[TaskItem] = Field(
        description="List of daily learning tasks",
    )


# ── Custom Exceptions ───────────────────────


class PlanExistsError(Exception):
    """Raised when an active (pending) plan for this book already exists."""


class TaskParsingError(Exception):
    """Raised when Ollama response cannot be parsed as the expected schema."""


# ── Helpers ───────────────────────


def _resolve_teaching_method(method: str) -> str:
    """Validate and normalise a teaching method; 'auto' → 'socratic'.

    Raises ValueError on bad input.
    """
    if method not in ALLOWED_TEACHING_METHODS:
        raise ValueError(
            f"Invalid teaching_method '{method}'. "
            f"Allowed: {sorted(ALLOWED_TEACHING_METHODS)}"
        )
    return "socratic" if method == "auto" else method


def _fetch_book_context(book_id: str, conn: sqlite3.Connection) -> dict[str, str]:
    """Fetch book metadata and first ~2000 chars of text.

    Returns {title, author, excerpt}.
    Raises ValueError if the book or its chunks do not exist.
    """
    row = conn.execute(
        "SELECT title, author FROM books WHERE id = ?",
        (book_id,),
    ).fetchone()
    if row is None:
        raise ValueError(f"Book {book_id} not found")

    title, author = row

    chunks = conn.execute(
        "SELECT content FROM book_chunks "
        "WHERE book_id = ? ORDER BY chunk_index ASC LIMIT ?",
        (book_id, 10),
    ).fetchall()

    if not chunks:
        raise ValueError(f"No chunks found for book {book_id}")

    excerpt_parts = [row[0] for row in chunks]
    merged = ""
    for part in excerpt_parts:
        stripped = part.strip()
        remaining = 2000 - len(merged)
        if remaining <= 0:
            break
        merged += stripped[:remaining]

    return {"title": title, "author": author, "excerpt": merged}


def _build_prompt(
    intent: str,
    context: dict[str, str],
    duration_days: int,
    teaching_name: str,
) -> tuple[str, str]:
    """Build (system_message, user_message) for Ollama.

    The system prompt includes the chosen teaching method's behavioural
    instructions so the model knows *how* to frame each task.
    """
    method_instr = _TEAChing_method_instructions.get(
        teaching_name, _TEAChing_method_instructions["socratic"]
    )

    system = (
        "You are a learning coach producing a SMART daily learning plan.\n\n"
        f"── Teaching method: {teaching_name} ──\n"
        f"{method_instr}\n\n"
        "Return ONLY valid JSON matching the schema below. No markdown code fences."
    )

    user = (
        f"User wants to learn from this book to achieve: '{intent}'\n\n"
        f"Book info:\n"
        f"- Title: {context['title']}\n"
        f"- Author: {context['author']}\n"
        f"- First ~2000 chars of content:\n\n"
        f"{context['excerpt']}\n\n"
        f"Create a total of {duration_days} tasks (one per day).\n\n"

        "For each task create a JSON object with exactly these fields:\n"
        "- day: integer from 1 to {duration_days}\n"
        '- title: brief descriptive label ≤ 50 chars '
        "(should reflect the teaching method, e.g. Socratic → 'Question about X')\n"
        "- description: detailed instructions ≥ 20 chars\n"
        "- estimated_minutes: integer between 5 and 45\n"
        '- exercise_type: one of "reading", "writing", "reflection", "review", "practice"\n'
        "- context_source: book title + chapter reference\n\n"

        "Return format:\n\n"
        '[\n'
        '  {\n'
        '    "day": 1,\n'
        '    "title": "...",\n'
        '    "description": "...",\n'
        '    "estimated_minutes": 30,\n'
        '    "exercise_type": "...",\n'
        '    "context_source": "..."\n'
        "  }\n"
        "]"
    )

    return (system, user)


# ── Main Forge Logic ───────────────────────


def forge_plan(
    book_id: str,
    intent: str,
    duration_weeks: int,
    teaching_method: str = DEFAULT_TEACHING_METHOD,
    db_path: Optional[str] = None,
) -> dict[str, Any]:
    """Generate a learning plan for an ingested book via Ollama.

    Args:
        book_id: UUID string of the ingested book.
        intent: User's stated goal ("Learn Python", "Master React").
        duration_weeks: Number of weeks (plan is 7 days/week).
        teaching_method: One of auto/socratic/feynman/analogical/spaced_recall.
            "auto" falls back to socratic.
        db_path: Optional SQLite path (default ~/.lifekit/lifekit.db).

    Returns:
        {plan_id, duration_weeks, task_count, teaching_method, fallback}.

    Raises:
        ValueError: book not found or bad teaching_method.
        PlanExistsError: a pending plan already exists for this book.
        RuntimeError: Ollama unreachable.
    """
    conn = get_connection(db_path)
    duration_days = duration_weeks * 7

    teaching_name = _resolve_teaching_method(teaching_method)

    # Guard against duplicate active plans.
    with conn:
        cur = conn.execute(
            "SELECT p.id FROM plans p "
            "JOIN tasks t ON t.plan_id = p.id "
            "WHERE p.book_id = ? AND t.status = 'pending' "
            "LIMIT 1",
            (book_id,),
        )
        if cur.fetchone():
            raise PlanExistsError(
                f"Active plan already exists for book {book_id}."
            )

    context = _fetch_book_context(book_id, conn)
    system_msg, user_msg = _build_prompt(intent, context, duration_days, teaching_name)

    ollama_model = os.getenv("OLLAMA_MODEL", "qwen3.8:27b-q8_0")
    try:
        resp = ollama.chat(
            model=ollama_model,
            messages=[
                {"role": "system", "content": system_msg},
                {"role": "user", "content": user_msg},
            ],
        )
        raw_text = resp["message"]["content"].strip()
    except (ollama.APIError, ConnectionRefusedError) as exc:
        raise RuntimeError(
            "Ollama not reachable. Is it running? Try: ollama serve"
        ) from exc

    # Validate or fall back.
    fallback_used = False
    try:
        plan = PlanResponse.model_validate_json(raw_text)
        task_list = plan.weekly_plan
    except Exception:
        print(
            f"Warning: Ollama did not return valid JSON. "
            f"Falling back to generic tasks for intent: {intent}"
        )
        fallback_text = raw_text[:500] if len(raw_text) > 500 else raw_text
        task_list = [
            TaskItem(
                day=i + 1,
                title="Read and reflect",
                description=fallback_text or "Reflect on the material for 30 minutes.",
                estimated_minutes=30,
                exercise_type="reading",
                context_source=f"{context['title']} by {context['author']}",
            )
            for i in range(min(duration_days, 7))
        ]
        fallback_used = True

    # Persist atomically.
    plan_id = uuid.uuid4().hex
    with conn:
        conn.execute(
            "INSERT INTO plans "
            "(id, book_id, user_intent, teaching_method, duration_weeks) VALUES (?, ?, ?, ?, ?)",
            (plan_id, book_id, intent, teaching_name, duration_weeks),
        )

        for task_obj in task_list:
            conn.execute(
                "INSERT INTO tasks "
                "(plan_id, day_number, title, description, estimated_minutes, "
                "exercise_type, context_source) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    plan_id,
                    task_obj.day,
                    task_obj.title,
                    task_obj.description,
                    task_obj.estimated_minutes,
                    task_obj.exercise_type,
                    task_obj.context_source or context["title"],
                ),
            )

    return {
        "plan_id": plan_id,
        "duration_weeks": duration_weeks,
        "task_count": len(task_list),
        "teaching_method": teaching_name,
        "fallback": fallback_used,
    }


if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Generate a learning plan from an ingested book."
    )
    parser.add_argument("book_id", help="UUID of the ingested book")
    parser.add_argument("--intent", "-i", required=True, help="User's learning intent")
    parser.add_argument(
        "--weeks", "-w",
        type=int,
        default=4,
        help="Duration in weeks (default 4 = 28 days)",
    )
    parser.add_argument(
        "--method",
        choices=["auto"] + sorted(ALLOWED_TEACHING_METHODS - {"auto"}),
        default="auto",
        help="Teaching method (default: auto, which uses socratic). "
             "Choices: socratic, feynman, analogical, spaced_recall",
    )
    args = parser.parse_args()

    try:
        result = forge_plan(
            book_id=args.book_id,
            intent=args.intent,
            duration_weeks=args.weeks,
            teaching_method=args.method,
        )
        method_label = result["teaching_method"].capitalize() if "fallback" not in args else "auto→socratic"
        print("Plan forged successfully!")
        print(f"  Plan ID: {result['plan_id']}")
        print(f"  Duration: {result['duration_weeks']} weeks ({result['task_count']} tasks)")
        print(f"  Method: {method_label}")
        if result.get("fallback"):
            print("  ⚠️ Fallback plan generated (Ollama response was invalid JSON)")
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except PlanExistsError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
